version: '3.9'

services:
  # Backend services
  backend:
    build:
      context: ./backend
    image: yoloback:v1.0
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - backend-data:/app/data
    networks:
      - yolo

  # Frontend service
  web:
    build:
      context: ./client
    image: yolofront:v1.0
    ports:
      - "4000:3000"
    depends_on:
      - backend # Added line specifying dependency
    environment:
      PORT: 3000
      MONGODB_URI: MongoDB://my-cloud-mongodb-instance:27017 
      DB_NAME: yolomy
    volumes:
      - frontend-data:/app/data
    networks:
      - yolo

volumes:
  backend-data:
  frontend-data:

networks:
  yolo:
    driver: bridge
