version: '3.9'

services:
  # Backend services
  backend:
    build:
      context: ./backend
    image: yoloback:yolobackend.v1.0.0
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - backend-data:/app/data
    networks:
      - yolo

  # Frontend services
  web:
    build:
      context: ./client
    image: yolofront:yolofrontend.v1.0.0
    ports:
      - "4000:3000"
    depends_on:
      - backend 
    environment:
      PORT: 3000
      MONGODB_URI: mongodb_uri 
      DB_NAME: yolomy
    volumes:
      - frontend-data:/app/data
    networks:
      - yolo

volumes:
  backend-data:
  frontend-data:

networks:
  yolo:
    driver: bridge
