- name: Setup Docker containers for e-commerce website
  hosts: all
  become: true

  tasks:
    - name: update apt cache
      apt:
        update_cache: true
      tags:
        - setup

    - name: Install Python packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - python-apt
        state: present
      tags:
        - setup
        - dependencies

    - name: Clone code from GitHub repository
      git:
        repo: https://github.com/CliffordIsaboke/yolo.git
        dest: /home/vagrant/myapp
        version: master
      register: git_clone

  roles:
    - role: client
      tags:
        - client
    - role: backend
      tags:
        - backend
