---
- name: Setup Docker containers for e-commerce website
  hosts: all
  become: true

  tasks:
    - name: Clone code from GitHub repository
      git:
        repo: https://github.com/CliffordIsaboke/yolo.git
        dest: /home/vagrant/myapp
        version: master
      register: git_clone

    - name: Install Python dependencies
      block:
        - name: Update APT cache
          apt:
            update_cache: yes
          tags:
            - setup

        - name: Install Python packages
          apt:
            name:
              - python3-pip
              - python3-dev
              - build-essential
              - python-apt
            state: present
          tags:
            - setup
            - dependencies

    - name: Build and start Docker containers
      docker_compose:
        project_name: myapp
        build:
          context: /home/vagrant/myapp/backend
          dockerfile: Dockerfile
        image: myapp:backend
        extra_args: --force-rm
        pull: no
        remove_image: no
        recreate: no
        state: present
        restart_policy: always
        volumes:
          - backend-data:/app/data
        ports:
          - "8081:8081"
        networks:
          - myapp

  vars:
    docker_compose_version: "1.29.2"
    mongodb_uri: MongoDB://my-cloud-mongodb-instance:27017
    mongodb_database: yolomy
    mongodb_collection: myCollection

  roles:
    - role: client
      tags:
        - client
    - role: backend
      tags:
        - backend
