- name: Setup Docker containers for e-commerce website
  hosts: all
  become: true

  tasks:
    - name: Install Python dependencies
      block:
        - name: Update APT cache
          apt:
            update_cache: yes
          tags:
            - setup

        - name: Install Python packages
          apt:
            name:
              - python3-pip
              - python3-dev
              - build-essential
              - python-apt
            state: present
          tags:
            - setup
            - dependencies
  vars:
    docker_compose_version: "1.29.2"
    mongodb_uri: "mongodb+srv://clifford:Cmo0KNN84HuMuftS@isaboke.wdbovod.mongodb.net/yolomy?retryWrites=true&w=majority"
    mongodb_database: "yolomy"
    mongodb_collection: "myCollection"

  roles:
    - role: client
      tags:
        - client
    - role: backend
      tags:
        - backend
    - role: database
      tags:
        - database
