apiVersion: v1
kind: Service
metadata:
  name: yolo
spec:
  selector:
    app: yolo
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: backend
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
