apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isaboke-demo-pv
spec:
  volumeName: isaboke-demo-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
