# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo_backend
  template:
    metadata:
      labels:
        app: yolo_backend
    spec:
      containers:
        - name: backend
          image: isaboke/yolofrontend:v1.0.0
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: server-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backendservice
spec:
  type: LoadBalancer
  selector:
    app: yolo_backend
  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
