apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
spec:
  volumeName: mongo-volume
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
